### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by raj-subhankar** [raj-subhankar/DownInsta#4]
MIT License https://opensource.org/licenses/MIT

**Comment by ventris** [comment]
I can help you with this.

**Comment by raj-subhankar** [comment]
@ventris thanks for the PR, but I think Github suggests the filename be LICENSE.txt or LICENSE, can you change that?

**Comment by ventris** [comment]
In their documentation about licensing there is (LICENSE.txt or LICENSE.md) https://help.github.com/articles/open-source-licensing/ 

I can change it if you prefer .txt instead.

**Comment by raj-subhankar** [comment]
@ventris sorry, my bad. .md is fine
