### ISSUE TITLE
Improve AboutActivity UI

### ISSUE THREAD

**Issue by raj-subhankar** [raj-subhankar/DownInsta#6]
Feel free to get creative. Add a screenshot of the changes made in comments.

**Comment by salRoid** [comment]
What kind of details you want on about activity app details , developer name , etc  ?

**Comment by raj-subhankar** [comment]
No names required, Add name of the app, put MIT license logo, Inform that its an open source app and add a link to the github repo.

**Comment by AggarwalAditya** [comment]
Can i work on this issue?

**Comment by raj-subhankar** [comment]
@AggarwalAditya Thanks for the interest, but this issue is closed now.
