### ISSUE TITLE
Change button UI

### ISSUE THREAD

**Issue by raj-subhankar** [raj-subhankar/DownInsta#9]
Change the "Reset" and "Paste URL" buttons to something more materialistic and matching with the current theme.

**Comment by vjs3** [comment]
@raj-subhankar can I work on this?

**Comment by raj-subhankar** [comment]
@vjs3 yes, go ahead

**Comment by satishm752-zz** [comment]
Can I work on this?

**Comment by raj-subhankar** [comment]
@satishm752 this was from last year bro. Closing this issue.

**Comment by satishm752-zz** [comment]
Ok. Can I use your project with modifications?
